import AppKit

/// Grab whatever the frontmost app has selected by synthesizing ⌘C, then put the user's
/// clipboard back exactly as it was.
///
/// This is the keyboard replacement for dragging something onto the shelf. It is only
/// reachable when the user has explicitly enabled EnhancedAccess — posting a key chord
/// into another application is the same permission that already backs ⌘V there.
///
/// ## Clipboard hygiene
///
/// Two writes reach the general pasteboard during one capture: the foreign app's copy,
/// and our restore. Both must stay out of clipboard histories.
///
/// - **Our own history** is deterministic: `ClipboardHistoryStore` capture is suspended
///   for the whole round-trip, so neither write can be recorded.
/// - **Third-party managers** are best-effort. The restore is marked so conforming
///   managers skip it (see `restoreMarkers`), but the foreign app's copy is written by
///   *that app*, so we cannot mark it. The only lever is time: managers poll (Maccy,
///   Raycast, and our own store all sit in the 0.2–1.0 s range), and the window here is
///   typically 30–150 ms, so a poll usually misses it. Usually is not always — a manager
///   that polls at exactly the wrong moment records one entry. That is inherent to
///   driving another app through the pasteboard and cannot be closed without Apple
///   Events, which would trade this race for a per-app TCC prompt.
///
/// After the restore the general pasteboard holds the user's original content again, so
/// nothing downstream sees the capture as a real copy. `changeCount` is higher, which is
/// unavoidable and carries no meaning beyond "something wrote".
@MainActor
enum PasteboardCapture {

    /// Ceiling on what we hold in memory to restore. Above this the clipboard is put
    /// back without the offending oversized representation rather than risking a
    /// multi-hundred-MB copy for a clipboard the user probably cannot paste anyway.
    private static let maxRestoreBytes = 32 * 1024 * 1024

    /// How long the frontmost app gets to service the synthesized ⌘C.
    private static let copyTimeout: Duration = .milliseconds(400)
    private static let pollInterval: Duration = .milliseconds(8)

    /// Markers put on the RESTORED content so conforming clipboard managers do not
    /// record it a second time.
    ///
    /// Deliberately NOT `TransientType`: per nspasteboard.org that means "this will be
    /// replaced or restored within seconds", which is true of the foreign app's copy but
    /// false of the restore — the restore is the final, lasting state, and a manager
    /// that believed otherwise could refuse to show the real clipboard.
    /// `AutoGeneratedType` is the accurate one ("the user did not intend this Copy") and
    /// `RestoredType` is the precise emerging convention for exactly this operation.
    private static let restoreMarkers = [
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.RestoredType",
    ]

    /// A verbatim copy of the general pasteboard: every item, every type.
    struct Snapshot {
        let items: [[NSPasteboard.PasteboardType: Data]]
        let changeCount: Int
        /// True when something was dropped for exceeding `maxRestoreBytes`.
        let lossy: Bool
    }

    // MARK: - Capture

    /// Result of one capture attempt. `nothingCopied` is distinct from failure: the
    /// frontmost app simply had nothing to give, and — importantly — the clipboard was
    /// never touched, so no restore happened and no history saw anything.
    enum Outcome {
        case captured([URL])
        case nothingCopied
        case notPermitted
    }

    /// Synthesize ⌘C in the frontmost app and turn whatever lands on the pasteboard into
    /// local file URLs ready for a session.
    static func captureSelection() async -> Outcome {
        guard EnhancedAccess.canPostEvents else { return .notPermitted }

        let pb = NSPasteboard.general
        let before = snapshot()

        // Suspend BEFORE posting: the foreign app's copy must not be recorded either.
        ClipboardHistoryStore.shared.beginSuppression()
        defer { ClipboardHistoryStore.shared.endSuppression() }

        guard EnhancedAccess.postCopyShortcut() else { return .notPermitted }

        guard await waitForChange(from: before.changeCount) else {
            // The app never answered — nothing was written, so there is nothing to put
            // back. Restoring anyway would add a pointless second changeCount bump.
            return .nothingCopied
        }

        // Read first, restore immediately after. The user's clipboard is whole again
        // within milliseconds — well before the session finishes opening.
        let urls = fileURLs(on: pb)
        let payload = urls.isEmpty ? DropMaterializer.capture(from: pb) : nil
        restore(before)

        if !urls.isEmpty { return .captured(urls) }
        // Text, a link, or an image becomes a real file through the same pipeline a drop
        // uses, so everything downstream is identical to a dragged asset.
        if let payload, let url = DropMaterializer.materialize(payload) {
            return .captured([url])
        }
        return .nothingCopied
    }

    private static func waitForChange(from changeCount: Int) async -> Bool {
        let deadline = ContinuousClock.now.advanced(by: copyTimeout)
        while ContinuousClock.now < deadline {
            if NSPasteboard.general.changeCount != changeCount { return true }
            try? await Task.sleep(for: pollInterval)
        }
        return false
    }

    private static func fileURLs(on pb: NSPasteboard) -> [URL] {
        let objects = pb.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL] ?? []
        return objects.filter { $0.isFileURL }
    }

    // MARK: - Snapshot / restore

    /// `pasteboard` is injectable so the fidelity of snapshot/restore can be tested
    /// against a private pasteboard instead of the user's live clipboard.
    static func snapshot(from pb: NSPasteboard = .general) -> Snapshot {
        var items: [[NSPasteboard.PasteboardType: Data]] = []
        var budget = maxRestoreBytes
        var lossy = false

        for item in pb.pasteboardItems ?? [] {
            var stored: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                // Reading resolves lazily-provided data. That is the point — a promise
                // is only valid while its provider lives, so it must be materialized now
                // or the restore would put back an empty husk.
                guard let data = item.data(forType: type) else { continue }
                guard data.count <= budget else { lossy = true; continue }
                budget -= data.count
                stored[type] = data
            }
            if !stored.isEmpty { items.append(stored) }
        }
        return Snapshot(items: items, changeCount: pb.changeCount, lossy: lossy)
    }

    static func restore(_ snapshot: Snapshot, to pb: NSPasteboard = .general) {
        guard !snapshot.items.isEmpty else {
            // The clipboard was genuinely empty before — leave it empty rather than
            // leaving the captured asset sitting there.
            pb.clearContents()
            return
        }

        var items: [NSPasteboardItem] = []
        for stored in snapshot.items {
            let item = NSPasteboardItem()
            for (type, data) in stored { item.setData(data, forType: type) }
            items.append(item)
        }
        // Markers ride on the first item because `NSPasteboard.types` reports that item's
        // types — which is what PasteboardPrivacy and most managers inspect.
        for marker in restoreMarkers {
            items[0].setData(Data(), forType: NSPasteboard.PasteboardType(marker))
        }

        pb.clearContents()
        pb.writeObjects(items)
    }
}
